name: 重新Fork-Lienol仓库
on:
  workflow_dispatch:

#  schedule:
#    - cron: 0 8 */5 * *

jobs: 
  build:
    runs-on: Ubuntu-20.04
    name: 重新Fork-Lienol仓库
    steps:
    - name: 重新拉取Lieno/openwrt仓库
      uses: danshui-git/github-forks-sync-action@main
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        upstream_repository: Lienol/openwrt
        upstream_branch: 19.07
        target_repository: zoranke/OpenWrt-build     #修改成你的帐号/仓库名字
        target_branch: Lienol                                #你仓库的分支
        force: true
        tags: false
